// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.9.0
// source: message.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	RemoteNodeInfo(ctx context.Context, in *RemoteServerNode, opts ...grpc.CallOption) (*RemoteServerNodeResponse, error)
	Send(ctx context.Context, opts ...grpc.CallOption) (Message_SendClient, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) RemoteNodeInfo(ctx context.Context, in *RemoteServerNode, opts ...grpc.CallOption) (*RemoteServerNodeResponse, error) {
	out := new(RemoteServerNodeResponse)
	err := c.cc.Invoke(ctx, "/proto.Message/RemoteNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) Send(ctx context.Context, opts ...grpc.CallOption) (Message_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[0], "/proto.Message/send", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSendClient{stream}
	return x, nil
}

type Message_SendClient interface {
	Send(*MessageEntity) error
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type messageSendClient struct {
	grpc.ClientStream
}

func (x *messageSendClient) Send(m *MessageEntity) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSendClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	RemoteNodeInfo(context.Context, *RemoteServerNode) (*RemoteServerNodeResponse, error)
	Send(Message_SendServer) error
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) RemoteNodeInfo(context.Context, *RemoteServerNode) (*RemoteServerNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteNodeInfo not implemented")
}
func (UnimplementedMessageServer) Send(Message_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_RemoteNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteServerNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).RemoteNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Message/RemoteNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).RemoteNodeInfo(ctx, req.(*RemoteServerNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServer).Send(&messageSendServer{stream})
}

type Message_SendServer interface {
	Send(*MessageResponse) error
	Recv() (*MessageEntity, error)
	grpc.ServerStream
}

type messageSendServer struct {
	grpc.ServerStream
}

func (x *messageSendServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSendServer) Recv() (*MessageEntity, error) {
	m := new(MessageEntity)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoteNodeInfo",
			Handler:    _Message_RemoteNodeInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "send",
			Handler:       _Message_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
